string = "hello"
number = 42
float = 3.14
boolean = true
dateTime = 1979-05-27T07:32:00-08:00
scientificNotation = 1e+12
multiLineString = """
are surrounded by three quotation marks
on each side and allow newlines.
"""
